# Generated by Django 3.2.2 on 2021-05-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodplannerapp', '0002_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(default='bla', max_length=200),
            preserve_default=False,
        ),
    ]
