# Generated by Django 3.2.2 on 2021-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodplannerapp', '0004_strengthmovement_wod_wodmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemas',
            name='schema_description',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
