# Generated by Django 3.2.2 on 2021-05-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodplannerapp', '0005_schemas_schema_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemas',
            name='schema_key',
            field=models.CharField(default='X', max_length=200),
            preserve_default=False,
        ),
    ]
