# Generated by Django 3.2.2 on 2021-05-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wodplannerapp', '0007_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='wod',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wodplannerapp.track'),
            preserve_default=False,
        ),
    ]
